In [ ]:
import numpy as np

In [ ]:
my_list=[1,2,3]

In [ ]:
arr=np.array(my_list)
arr

array([1, 2, 3])

In [ ]:
wrong_matrix = [[1,2,3],[4,5,6],[7,8,9]] #it is not a matrix
wrong_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(wrong_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)# 2 stepsize

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))#2 dimension

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.linspace(0,5,10)#1 dimension, 10 number of points

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.randn(2) #-1 and 1

array([-0.95956188,  0.36550442])

In [ ]:
np.random.randn(5,5)

array([[ 1.25283152,  1.22256974, -0.5231276 , -0.63256505, -0.37302084],
       [-1.68663599, -1.8351733 , -1.76438555, -0.56793634,  1.0340423 ],
       [-1.3853284 ,  0.03572271, -1.46216274,  0.19591357,  0.84553182],
       [ 0.35843612, -0.87444492,  0.88214888,  0.39119752,  0.10835221],
       [-0.63082178,  1.62566134,  0.59539054,  1.25182962,  0.14195574]])

In [ ]:
np.random.randint(1,100)

95

In [ ]:
np.random.randint(1,100,10)

array([51, 26, 79, 74, 13, 90, 41, 18, 31, 73])

In [ ]:
np.random.randint(1,100,(5,5))

array([[95,  6, 91, 33, 34],
       [35, 18, 52, 81, 46],
       [43, 10, 55, 82, 97],
       [90, 17, 46, 83, 63],
       [84, 96, 69, 76, 96]])

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([32, 18, 24, 26, 10,  8, 40, 35, 22, 44])

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr #even though its shape is changed it still what it is at the beginning

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([32, 18, 24, 26, 10,  8, 40, 35, 22, 44])

In [ ]:
ranarr.max()

44

In [ ]:
ranarr.argmax()

9

In [ ]:
ranarr.min()

8

In [ ]:
ranarr.argmin()

5

In [ ]:
ranarr.sort()

In [ ]:
ranarr #reshape vs sort.

array([ 8, 10, 18, 22, 24, 26, 32, 35, 40, 44])

In [ ]:
# Vector no dimension if (x, )
arr.shape

(25,)

In [ ]:
 #Notice the two sets of brackets
arr.reshape(1,25)  #[[]] first inside we have one element when we enter second [ ] there are 25 elements#

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.dtype

dtype('int64')

#**Numpy indexing and selection**

In [ ]:
a=np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a[8]

8

In [ ]:
a[1:5]

array([1, 2, 3, 4])

In [ ]:
a[:6]

array([0, 1, 2, 3, 4, 5])

In [ ]:
a[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Setting a value with index range (Broadcasting)
a[0:3]=15
a

array([15, 15, 15,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Reset array
a = np.arange(0,11)
#Show
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Slices
slice_of_a = a[0:6]
#Show slice
slice_of_a

array([0, 1, 2, 3, 4, 5])

In [ ]:
#Change Slice
slice_of_a[:]=99
#Show Slice again
slice_of_a

array([99, 99, 99, 99, 99, 99])

In [ ]:
#Now note the changes also occur in our original array!
a

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
#Data is not copied, it's a view of the original array! This avoids memory problems!
#To get a copy, need to be explicit
a_copy = a.copy()
a_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
a_copy[:]=100
a_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
a

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
a_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
a_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
a_2d[0][0]

5

In [ ]:
a_2d[2][1]

40

In [ ]:
a_2d[2,1]

40

In [ ]:
a_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
#Shape bottom row
a_2d[2,:]

array([35, 40, 45])

In [ ]:
#Selection
b=np.arange(1,11)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#short way
b[b>5]

array([ 6,  7,  8,  9, 10])

In [ ]:
c_2d=np.arange(0,50).reshape(5,10)
c_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
c_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

#**Numpy Operations**

In [ ]:
arr = np.arange(0,10)
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
# Also warning, but not an error instead infinity
1/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.max(arr) #same as arr.max()

9

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

#**Exercises**

In [ ]:
import numpy as np

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
5*np.ones(10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Use NumPy to generate a random number between 0 and 1
np.random.rand(1)

array([0.2563827])

In [ ]:
#Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
np.random.randn(25)


array([-1.06460756, -1.54892581, -1.56079788, -1.85143373, -0.82438264,
       -0.48661874, -1.00468869,  1.42080639,  0.1416217 ,  0.29727279,
       -0.50322143,  0.21762316,  0.37340865,  0.34876588, -0.66167528,
        0.1823706 , -0.19575246, -0.38418423,  1.81590038, -1.39838857,
        1.56354539,  0.50203042,  2.44244312,  2.55862036, -0.42328201])

In [ ]:
np.arange(1,101).reshape(10,10) / 100


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
mat[3,4]

20

In [ ]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [ ]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
#sum of all values.
np.sum(mat[:])

325

In [ ]:
np.std(mat[:])

7.211102550927978

In [ ]:
#the sum of all the columns in mat
mat.sum(axis=0)

array([55, 60, 65, 70, 75])